/**************************************************************************
** GENERAL.H
**
** Contains general definitions used by most C files.
**************************************************************************/

#ifndef _GENERAL_H_
#define _GENERAL_H_

#ifndef TRUE
#define  TRUE    1
#endif
#ifndef FALSE
#define  FALSE   0
#endif

typedef unsigned char byte;
typedef unsigned short int word;
typedef char boolean;

#endif  /* _GENERAL_H_ */
